## Numpy library exercises

In [4]:
import numpy as np

**1.** Given a random array, negate the sign of the elements whose values are between 3 and 8

In [7]:

array = np.array(np.random.randint(0, 12+1, size=(1, 10)))
print(array)

# works for any array
nArray = np.where((array > 3) & (array < 8), np.negative(array), array)
print(nArray)

[[ 2  6  9  3  1  3 10 10  9 12]]
[[ 2 -6  9  3  1  3 10 10  9 12]]


**2.** Replace the maximum element of a random array with 0

In [ ]:
import numpy as np
array = np.array(np.random.randint(0, 12+1, size=(1, 10)))
print(array)

# works for any array (since not specified, I replace all occurrences of the maximum value with 0)
zeroArray = np.where(array == np.max(array), 0, array)
print(zeroArray)

[[9 3 6 5 0 1 4 0 1 2]]
[[0 3 6 5 0 1 4 0 1 2]]


**3.** Build the direct (Cartesian) product of arrays (all combinations with each element). A two-dimensional array is given as input

In [151]:
# your code

**4.** Given 2 arrays A (8x3) and B (2x2). Find the rows in A that contain elements from each row of B, regardless of the order of elements in B

In [152]:
# your code

**5.** Given a 10x3 matrix, find the rows made up of unequal values (for example, the row [2,2,3] is kept, the row [3,3,3] is removed)

In [153]:
# your code

**6.** Given a two-dimensional array. Remove the rows that are duplicated

In [154]:
# your code

______
______

For each of the following tasks (1-5) you need to provide 2 implementations – one without using numpy (assume that wherever a numpy array should be the input or output, plain lists will be used instead), and a second one that is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ You may assume that all specified objects are non-empty (for instance, in __Task 1__ there are non-zero elements on the matrix diagonal).

__Note 2.__ For most tasks the solution takes no more than 1-2 lines.

___

* __Task 1__: Compute the product of the non-zero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) the answer is 3.

In [156]:
# your code

* __Task 2__: Given two vectors x and y. Check whether they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) the answer is True.

In [157]:
# your code

* __Task 3__: Find the maximum element in vector x among the elements that are preceded by a zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) the answer is 5.

In [158]:
# your code

* __Task 4__: Implement run-length encoding. For some vector x, return a tuple of two vectors of the same length. The first contains the numbers, and the second - how many times each of them should be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) the answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [159]:
# your code

* __Task 5__: Given two samples of objects - X and Y. Compute the matrix of Euclidean distances between the objects. Compare it with the scipy.spatial.distance.cdist function in terms of execution speed.

In [160]:
# your code

_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new kind of tasty, healthy cereal called **CrunchieMunchies**.

You want to demonstrate to consumers how healthy your cereal is compared to other leading brands, so you have collected nutrition data on several different competitors.

Your task is to use Numpy computations to analyze this data and prove that your **CrunchieMunchies** are the healthiest choice for consumers.


In [77]:
import numpy as np

1. Look at the file cereal.csv. This file contains the calorie counts for various brands of cereal. Load the data from the file and save it as calorie_stats.

In [170]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. A single serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Save the answer in the variable average_calories and print the variable in the terminal

In [161]:
# your code

3. Does the average calorie count correctly reflect the distribution of the dataset? Let's sort the data and take a look.

Sort the data and save the result in the variable calorie_stats_sorted. Print the sorted information

In [162]:
# your code

4. It looks like most of the values are above the average. Let's see whether the median is a more accurate measure for the dataset.

Compute the median of the dataset and save your answer in median_calories. Print the median so you can see how it compares to the average.

In [163]:
# your code

5. While the median shows that at least half of our values are above 100 calories, it would be more impressive to show that a significant portion of competitors have a higher calorie count than CrunchieMunchies.

Compute various percentiles and print them until you find the smallest percentile that exceeds 60 calories. Save this value in the variable nth_percentile.

In [164]:
# your code

6. Although the percentile shows us that most competitors have a much higher calorie count, it is an inconvenient concept to use in marketing materials.

Instead, let's compute the percentage of cereals that contain more than 60 calories per serving. Save your answer in the variable more_calories and print it

In [165]:
# your code

7. That's a really high percentage. This will be very useful when we promote CrunchieMunchies. But one question is: how large are the differences in the dataset? Can we make the generalization that most cereals contain about 100 calories, or is the spread even larger?

Compute the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it in the terminal. How can we incorporate this value into our analysis?

In [166]:
# your code

8. Write a short paragraph summarizing your findings and how you think this data could be used to benefit MyCrunch in marketing CrunchieMunchies.

In [167]:
# your code