## Numpy Library Exercises

In [2]:
import numpy as np

**1.** Given a random array, change the sign of elements whose values ​​are between 3 and 8

In [ ]:
array = np.array(np.random.randint(0, 12+1, size=(1, 10)))
print(array)

# works for any array
nArray = np.where((array > 3) & (array < 8), np.negative(array), array)
print(nArray)

**2.** Replace the maximum element of a random array with 0

In [ ]:
array = np.array(np.random.randint(0, 12+1, size=(1, 10)))
print(array)

# works for any array (since not specified, I replace all occurrences of the maximum value with 0)
zeroArray = np.where(array == np.max(array), 0, array)
print(zeroArray)

**3.** Construct the direct product of arrays (all combinations with each element). A two-dimensional array is provided as input.

In [50]:
array = np.array(np.random.randint(0, 12+1, size=(2, 3)))
print(array)

arrCom = np.array(np.meshgrid(*array)).T.reshape(-1, len(array))
print(f"Combinations: {arrCom}")

[[ 0  1 12]
 [ 6 11  5]]
Combinations: [[ 0  6]
 [ 0 11]
 [ 0  5]
 [ 1  6]
 [ 1 11]
 [ 1  5]
 [12  6]
 [12 11]
 [12  5]]


**4.** Given two arrays, A (8x3) and B (2x2), find rows in A that contain elements from each row in B, regardless of the order of the elements in B.

In [47]:
arrayA = np.array(np.random.randint(0, 12+1, size=(8, 3)))
print(f"Array A: {arrayA}")
arrayB = np.array(np.random.randint(0, 12+1, size=(2, 2)))
print(f"Array B: {arrayB}")

rowsOfAWithAnyFromEachRowOfB = np.array([row for row in arrayA if all(np.isin(row, b).any() for b in arrayB)])
print(f"Rows of A with any from each row of B: {rowsOfAWithAnyFromEachRowOfB}")


Array A: [[ 5  4 11]
 [10  3 12]
 [ 4 12  6]
 [ 5 11  4]
 [ 3 10  8]
 [ 3  5 10]
 [11  3  9]
 [ 4  8  3]]
Array B: [[5 3]
 [9 4]]
Rows of A with any from each row of B: [[ 5  4 11]
 [ 5 11  4]
 [11  3  9]
 [ 4  8  3]]


**5.** Given a 10x3 matrix, find rows of unequal values ​​(for example, the row [2,2,3] remains, the row [3,3,3] is deleted)

In [ ]:
array = np.array(np.random.randint(0, 3, size=(10, 3)))
print(array)

withoutRowsWithEqualValues = np.array([row for row in array if np.unique(row).size > 1])
print(f"Array without rows with equal values: {withoutRowsWithEqualValues}")


**6.** Given a two-dimensional array, remove the rows that are repeated.

In [ ]:
array = np.array(np.random.randint(0, 3, size=(10, 2)))
print(array)

noRepetitions = np.unique(array, axis=0)
print(f"Array without repetitions: {noRepetitions}")

______
______

For each of the following problems (1-5) you need to provide 2 implementations – one without using numpy (Consider that where the input or output should be a numpy array, there will simply be lists), and the second one is fully vectorized using numpy (without using Python loops/map/list comprehension).


__Note 1.__ It can be assumed that all specified objects are non-empty (for example, in __task 1__ there are non-zero elements on the diagonal of the matrix).

__Note 2.__ For most tasks, the solution takes no more than 1-2 lines.

___

* __Task 1__: Calculate the product of nonzero elements on the diagonal of a rectangular matrix.  
 For example, for X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) answer is 3.

In [59]:
#X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
x = np.array(np.random.randint(0, 8, size=(3, 3)))
print(x)
#numpy
diagonal_product = np.prod(np.where(np.diagonal(x) != 0, np.diagonal(x), 1))
print(f"Diagonal product of X: {diagonal_product}")
#nonumpy
diagonal_product_nonp = 1
for i in range(min(len(x), len(x[0]))):
    if x[i][i] != 0:
        diagonal_product_nonp *= x[i][i]
print(f"Diagonal product of X (nonumpy): {diagonal_product_nonp}")



[[5 1 7]
 [5 4 7]
 [1 7 5]]
Diagonal product of X: 100
Diagonal product of X (nonumpy): 100


* __Task 2__: Two vectors x and y are given. Check if they define the same multiset.  
  For example, for x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) answer is True.

In [60]:
#numpy
x = np.array([1,2, 2, 4])
y = np.array([4,2,1,2])

npEqiv = np.array_equal(np.sort(x), np.sort(y))
print(npEqiv)   

#nonumpy
x = [1,2, 2, 4]
y = [4,2,1,2]
nonNpEqiv = (sorted(x) == sorted(y))
print(nonNpEqiv)

True
True


* __Task 3__: Find the maximum element in the vector x among the elements preceded by zero. 
 For example, for x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) answer is 5.

In [61]:
#numpy
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

zeroIndices = np.where(x == 0)[0]
zeroIndices = zeroIndices[zeroIndices < x.size-1]
maxAfterZero = np.max(x[zeroIndices+1])
print(maxAfterZero)

#nonumpy
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
maxAfterZeroNoNp = max([x[i+1] for i in range(len(x)-1) if x[i] == 0])
print(maxAfterZeroNoNp)

5
5


* __Task 4__: Implement run-length encoding. For some vector x, it is necessary to return a tuple of two vectors of the same length. The first one contains numbers and the second one contains how many times they need to be repeated.  
 For example, for x = np.array([2, 2, 2, 3, 3, 3, 5]) answer is (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [62]:
#numpy
x = np.array([2, 2, 2, 3, 3, 3, 2, 5])

changeIndices = np.where(x[1:] != x[:-1])[0] + 1
indices = np.r_[0, changeIndices, x.size]
values = x[indices[:-1]]
lengths = np.diff(indices)
encoding = (values, lengths)

print(encoding)

#nonumpy
x = [2, 2, 2, 3, 3, 3, 2, 5]
currVal = None
count = 0
values = []
lengths = []
for v in x:
    if v != currVal:
        values.append(v)
        if count != 0:
            lengths.append(count)
        count = 1
        currVal = v
    else:
        count+=1
lengths.append(count)
encoding = (values, lengths)
print(encoding)

(array([2, 3, 2, 5]), array([3, 3, 1, 1]))
([2, 3, 2, 5], [3, 3, 1, 1])


* __Task 5__: Two samples of objects are given - X and Y. Calculate the matrix of Euclidean distances between objects. Compare with function scipy.spatial.distance.cdist by operating speed.

In [71]:
# numpy
X = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6],[0.7,0.8,0.9],[0.1,0.4,0.7],[0.2,0.5,0.8]])
Y = np.array([[0.5,0.5,0.5],[0.1,0.2,0.3],[0.4,0.2,0.4],[0.9,0.9,0.9]])
distanceNp = np.sqrt(((X[:,None,:] - Y[None,:,:])**2).sum(axis=2))
print(distanceNp, "\n")

# nonumpy — same data as lists
Xl = X.tolist()
Yl = Y.tolist()
distanceList = [[sum((a-b)**2 for a,b in zip(xi, yj))**0.5 for yj in Yl] for xi in Xl]
for entry in distanceList:
    print(entry)

# sanity check — two separate comparisons against cdist
from scipy.spatial.distance import cdist
ref = cdist(X, Y)
print(np.allclose(distanceNp, ref) and np.allclose(distanceList, ref))  # -> True

%timeit np.sqrt(((X[:,None,:] - Y[None,:,:])**2).sum(axis=2))
%timeit [[sum((a-b)**2 for a,b in zip(xi, yj))**0.5 for yj in Yl] for xi in Xl]
%timeit cdist(X, Y)




[[0.53851648 0.         0.31622777 1.22065556]
 [0.14142136 0.51961524 0.36055513 0.70710678]
 [0.53851648 1.03923048 0.83666003 0.2236068 ]
 [0.45825757 0.4472136  0.46904158 0.96436508]
 [0.42426407 0.59160798 0.53851648 0.81240384]] 

[0.5385164807134505, 0.0, 0.316227766016838, 1.2206555615733703]
[0.14142135623730948, 0.5196152422706632, 0.3605551275463989, 0.7071067811865476]
[0.5385164807134505, 1.0392304845413265, 0.8366600265340756, 0.22360679774997902]
[0.45825756949558405, 0.4472135954999579, 0.4690415759823429, 0.9643650760992956]
[0.42426406871192857, 0.5916079783099616, 0.5385164807134505, 0.812403840463596]
True
4.27 μs ± 163 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
15.6 μs ± 1.04 μs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
2.05 μs ± 204 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


_______
________

* #### __Task 6__: CrunchieMunchies __*__

You work in the marketing department of a food company called MyCrunch, which is developing a new type of delicious, healthy cereal called **CrunchieMunchies**.

You want to show consumers how healthy your cereal is compared to other leading brands, so you've compiled nutrition data from several different competitors.

Your task is to use Numpy calculations to analyze this data and prove that your **СrunchieMunchies** - the healthiest choice for consumers.


In [3]:
import numpy as np

1. View the cereal.csv file. This file contains calorie counts for various brands of cereal. Download the data from the file and save it as calorie_stats.

In [29]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. One serving of CrunchieMunchies contains 60 calories. How much higher is the average calorie count of your competitors?

Store the answer in the variable average_calories and print the variable in the terminal

In [43]:
# your code
avg = np.average(calorie_stats)
print(f"Average = {avg} calories")
average_calories = avg - 60
print(f"Average is higher by {average_calories} calories")

Average = 106.88311688311688 calories
Average is higher by 46.883116883116884 calories


3. Does the average calorie count accurately reflect the distribution of the data set? Let's sort the data and see.

Sort the data and store the result in the calorie_stats_sorted variable. Print the sorted information.

In [14]:
# your code
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. It looks like most values ​​are above the mean. Let's see if the median is the most accurate measure of the data set.

Calculate the median of the data set and save your answer in median_calories. Print the median so you can see how it compares to the mean.

In [ ]:
median = np.median(np.sort(calorie_stats))
print(f"Median: {median} calories")




Median: 110.0


5. While the median shows that at least half of our values ​​are over 100 calories, it would be more impressive to show that a significant portion of the competitors have higher calorie counts than CrunchieMunchies.

Calculate various percentiles and print them until you find the lowest percentile that exceeds 60 calories. Store this value in the nth_percentile variable.

In [ ]:
for i in range(1, 101):
    p = np.percentile(calorie_stats, i)
    print(f"{i}th percentile: {p}")
    if p > 60:
        nth_percentile = p
        break

print(f"\nLowest percentile exceeding 60 calories: {nth_percentile} - percentile {i}")

1th percentile: 50.0
2th percentile: 50.0
3th percentile: 55.599999999999994
4th percentile: 70.0

Lowest percentile exceeding 60 calories: 70.0 - percentile 4


6. While the percentile shows us that most competitors have much higher calorie counts, it's an awkward concept to use in marketing materials.

Instead, let's calculate the percentage of cereals that contain more than 60 calories per serving. Save your answer in the more_calories variable and print it.

In [45]:
more_calories = np.average(calorie_stats > 60) * 100
print(f"{more_calories:.2f}% of cereals have more than 60 calories")

96.10% of cereals have more than 60 calories


7. This is a really high percentage. This will be very useful as we promote CrunchieMunchies. But one question is: how big are the differences in the dataset? Can we generalize that most cereals contain around 100 calories or is the range even wider?

Calculate the magnitude of the deviation by finding the standard deviation. Save your answer in calorie_std and print it on the terminal. How can we incorporate this value into our analysis?

In [ ]:
calorie_std = np.std(calorie_stats)
print(f"Standard deviation: {calorie_std}")

# Std is around 19.36, while the previously average mean is around 106.88 calories.
# Since std is relatively low - around 20% of the mean, we can safely generalize that most cereals contain around 100 calories.

Standard deviation: 19.35718533390827


8. Please write a short paragraph outlining your findings and how you believe this data can be used to Mycrunch's advantage in marketing CrunchieMunchies.

In [ ]:
""" 
Since the intended result is to promote CrunchieMunchies as a "healthier" option than the competition,
the obtained data can be helpful in proving that point. Both the mean and median values can work as 
good entry points, the biggest eye catcher is the percentage of cereals that have more than 60 calories -
it shows that CrunchieMunchies is a better choice than most of the competition. Percentiles and standard
deviation are more technical data, which mostly support other claims.
"""